### ISSUE TITLE
Load Layer - Native title determination map - update

### ISSUE THREAD

**Issue by rp-ala** [AtlasOfLivingAustralia/layers-service#72]
Loaded already, but needs updating
spatial boundaries of areas/part areas protected by Native Title
www.nntt.gov.au/

**Comment by ansell** [comment]
Spatial data reference at:

http://www.nntt.gov.au/assistance/Geospatial/Pages/Spatial-aata.aspx

With downloads (including other shapefiles together with the RATSIB Areas) at:

http://www.ntv.nntt.gov.au/intramaps/download/download.asp

**Comment by ansell** [comment]
Existing layer at:

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/2009

Only currently using the NAME field:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl2009

Only has 58 unique NAME values right now, where the version on the nntt website has 346 unique values for its NAME field.

Going to add a new layer based on those differences and the download URL for cl2009 being completely different, seemingly based on a search string:

http://asdd.ga.gov.au/asdd/tech/zap/basic-full.zap?&target=ga-1&syntax=html&cclfield1=all&cclfield2=phrase&cclfield3=any&cclterm1=native%20title%20determination&cclterm2=&cclterm3=&start=1&number=1

**Comment by ansell** [comment]
Loaded to spatial-test

http://spatial-test.ala.org.au/spatial-service/manageLayers/layer/10840

NAME field:

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl10840

RNTBCNAME field (Registered Native Title Body Corporate):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl110840

DETOUTCOME field (Determination Outcome):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl210840

**Comment by ansell** [comment]
Also added:

DETMETHOD (Determination method):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl310840

DETTYPE (Determination type):

http://spatial-test.ala.org.au/spatial-service/manageLayers/field/cl410840

**Comment by ansell** [comment]
Hi @adam-collins , could you review these National Native Title Tribunal fields during the spatial sprint but not push them across to production until the Cassandra 3 + Solr 5/6 changes have been completed to ensure we don't push record sizes past their current limit.

**Comment by ansell** [comment]
The current plan was to replace one field currently in the biocache with exactly one of the fields from this new layer. However, there is a complication. The polygons included currently for the NAME attribute include all polygons, including those where the DETOUTCOME (Determination Outcome) attribute indicated that native title wasn't present. It may be confusing to annoate biocache records with the NAME when the outcome was not conclusively that native title was present, because I am not able to push all of the fields into the biocache right now which would clarify the situation.

To avoid that confusion, I am going to create a new layer, just for NAME, where I filter out the polygons where DETOUTCOME indicated native title was not present. 

Once I have done that, I will disable the "Include in Biocache" for the previous native title layer/field, cl2009.

Then this new filtered layer would then be pushed across to spatial.ala.org.au and would be included in the next full sample/process for the biocache.

**Comment by ansell** [comment]
@adam-collins cl2009 has not been updated. The 10840 fields have all been loaded into spatial-test and are urgently required by @StephanievG for a conference next week. I have switched off the biocache index field so they won't affect biocache index sizes. Refs https://github.com/AtlasOfLivingAustralia/seasonal-calendar/issues/39

**Comment by kheerand** [comment]
*This came through today from Ely.  Not sure if there is a separate issue for Stephanie's request or not but I'm putting it here so we don't loose track of it if it is not there anywhere else.*

Hi team,
I've just been in a meeting with Stephanie von Gavel (previously of ALA now with Land and Water) and she reported that she's been asking to have the spatial portal updated with new indigenous protected areas layer. She said that she's recently sent a reminder email. I'm just wondering if that email went to any of you? 

I also can't find this request logged anywhere in GitHub (but that doesn't mean it's not there) and it's not on the Kanban board for your outcome theme.

If this request isn't yet in the system could it please be added? Stephanie mentioned Miles as one of the people she sent her recent email to. She also said that the data you'll need is in data.gov.au 

Thanks, Ely

**Comment by Tasilee** [comment]
How does this relate to https://data.gov.au/dataset/ds-dga-ecdbbb6c-c374-4649-9cd3-0677f44182c9/details?q=native%20title?
